# Generated by Django 5.0 on 2024-10-30 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipos_de_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tipos_de_planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_plan', models.CharField(max_length=15)),
                ('duracion_meses', models.DurationField()),
                ('valor', models.FloatField()),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tipo_pagos')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=10)),
                ('contraseña', models.CharField(max_length=16)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tipos_de_planes')),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tipos_de_usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='sugerencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_i', models.CharField(max_length=15)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('fecha', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='categoria_gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_g', models.CharField(max_length=15)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuarios')),
            ],
        ),
    ]
